name: SimpleTask
version: '${version}'
main: dev.user.simpletask.SimpleTaskPlugin
api-version: '1.21'
folia-supported: true
author: user
description: A simple daily task system for Folia/Paper servers

softdepend:
  - XConomy
  - CraftEngine

commands:
  task:
    description: Open the daily task GUI
    usage: /task
    aliases: [dailytask, dt]
  taskadmin:
    description: Admin commands for SimpleTask
    usage: /taskadmin <reload|import|list|add|edit|delete>
    permission: simpletask.admin
    aliases: [tadmin]

permissions:
  simpletask.admin:
    description: Allows access to admin commands
    default: op
  simpletask.use:
    description: Allows using the daily task GUI
    default: true
